// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HIE8Lv4_Y9d2cSB9ifGNUACZlsPNURo',
    appId: '1:806788436922:web:4e663bed8e0fe13ffb4383',
    messagingSenderId: '806788436922',
    projectId: 'flutter-firebase-75fab',
    authDomain: 'flutter-firebase-75fab.firebaseapp.com',
    storageBucket: 'flutter-firebase-75fab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1TRdOgAkTJDr8RGpHoi-skxAKEqqxr6o',
    appId: '1:806788436922:android:b35f706b377c2f01fb4383',
    messagingSenderId: '806788436922',
    projectId: 'flutter-firebase-75fab',
    storageBucket: 'flutter-firebase-75fab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSntWjXzp2QTs99lH0OgvtL80H-ZgoThY',
    appId: '1:806788436922:ios:429d54f54277e026fb4383',
    messagingSenderId: '806788436922',
    projectId: 'flutter-firebase-75fab',
    storageBucket: 'flutter-firebase-75fab.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSntWjXzp2QTs99lH0OgvtL80H-ZgoThY',
    appId: '1:806788436922:ios:429d54f54277e026fb4383',
    messagingSenderId: '806788436922',
    projectId: 'flutter-firebase-75fab',
    storageBucket: 'flutter-firebase-75fab.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3HIE8Lv4_Y9d2cSB9ifGNUACZlsPNURo',
    appId: '1:806788436922:web:e498eb958bcf8c9cfb4383',
    messagingSenderId: '806788436922',
    projectId: 'flutter-firebase-75fab',
    authDomain: 'flutter-firebase-75fab.firebaseapp.com',
    storageBucket: 'flutter-firebase-75fab.firebasestorage.app',
  );
}
